spring.application.name=gateway
server.port=8080
spring.main.web-application-type=reactive

spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.name=gateway

management.endpoints.web.exposure.include=gateway,health,info
management.endpoint.gateway.enabled=true
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8181/realms/fitness-oauth2/protocol/openid-connect/certs
