server.port=8083

spring.mongodb.uri=mongodb://localhost:27017/fitnessRecommendation

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

rabbitmq.exchange.name=fitness.exchange
rabbitmq.queue.name=activity.queue
rabbitmq.routing.key=activity.tracking

rabbitmq.username=guest
rabbitmq.password=guest
rabbitmq.host=localhost
rabbitmq.port=5672

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}

# Resilience4J Circuit Breaker Config
resilience4j.circuitbreaker.instances.gemini.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.gemini.slidingWindowSize=10
resilience4j.circuitbreaker.instances.gemini.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.gemini.failureRateThreshold=50
resilience4j.circuitbreaker.instances.gemini.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.gemini.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.gemini.slidingWindowType=COUNT_BASED

# Resilience4J Retry Config
resilience4j.retry.instances.gemini.maxAttempts=3
resilience4j.retry.instances.gemini.waitDuration=1s
resilience4j.circuitbreaker.circuitBreakerAspectOrder=1
resilience4j.retry.retryAspectOrder=2
